from newsapi.const import countries, categories, languages


class Constants:
    # 'zh': '',
    COUNTRY_CODE = [{'id': 'ae', 'text': 'United Arab Emirates'},
                    {'id': 'ar', 'text': 'Argentina'},
                    {'id': 'at', 'text': 'Austria'},
                    {'id': 'au', 'text': 'Australia'},
                    {'id': 'be', 'text': 'Belgium'},
                    {'id': 'bg', 'text': 'Bulgaria'},
                    {'id': 'br', 'text': 'Brazil'},
                    {'id': 'ca', 'text': 'Canada'},
                    {'id': 'ch', 'text': 'Switzerland'},
                    {'id': 'cn', 'text': 'China'},
                    {'id': 'co', 'text': 'Colombia'},
                    {'id': 'cu', 'text': 'Cuba'},
                    {'id': 'cz', 'text': 'Czech Republic'},
                    {'id': 'de', 'text': 'Germany'},
                    {'id': 'eg', 'text': 'Egypt'},
                    {'id': 'es', 'text': 'Spain'},
                    {'id': 'fr', 'text': 'France'},
                    {'id': 'gb', 'text': 'United Kingdom'},
                    {'id': 'gr', 'text': 'Greece'},
                    {'id': 'hk', 'text': 'Hong Kong'},
                    {'id': 'hu', 'text': 'Hungary'},
                    {'id': 'id', 'text': 'Indonesia'},
                    {'id': 'ie', 'text': 'Ireland'},
                    {'id': 'il', 'text': 'Israel'},
                    {'id': 'in', 'text': 'India'},
                    {'id': 'is', 'text': 'Iceland'},
                    {'id': 'it', 'text': 'Italy'},
                    {'id': 'jp', 'text': 'Japan'},
                    {'id': 'kr', 'text': 'Korea, Republic of'},
                    {'id': 'lt', 'text': 'Lithuania'},
                    {'id': 'lv', 'text': 'Latvia'},
                    {'id': 'ma', 'text': 'Morocco'},
                    {'id': 'mx', 'text': 'Mexico'},
                    {'id': 'my', 'text': 'Malaysia'},
                    {'id': 'ng', 'text': 'Nigeria'},
                    {'id': 'nl', 'text': 'Netherlands'},
                    {'id': 'no', 'text': 'Norway'},
                    {'id': 'nz', 'text': 'New Zealand'},
                    {'id': 'ph', 'text': 'Philippines'},
                    {'id': 'pk', 'text': 'Pakistan'},
                    {'id': 'pl', 'text': 'Poland'},
                    {'id': 'pt', 'text': 'Portugal'},
                    {'id': 'ro', 'text': 'Romania'},
                    {'id': 'rs', 'text': 'Serbia'},
                    {'id': 'ru', 'text': 'Russian Federation'},
                    {'id': 'sa', 'text': 'Saudi Arabia'},
                    {'id': 'se', 'text': 'Sweden'},
                    {'id': 'sg', 'text': 'Singapore'},
                    {'id': 'si', 'text': 'Slovenia'},
                    {'id': 'sk', 'text': 'Slovakia'},
                    {'id': 'th', 'text': 'Thailand'},
                    {'id': 'tr', 'text': 'Turkey'},
                    {'id': 'tw', 'text': 'Taiwan, Province of China'},
                    {'id': 'ua', 'text': 'Ukraine'},
                    {'id': 'us', 'text': 'United States'},
                    {'id': 've', 'text': 'Venezuela, Bolivarian Republic of'},
                    {'id': 'za', 'text': 'South Africa'}]

    # 'cn': 'Czech',
    LANGUAGE_CODE = [{'id': 'ar', 'text': 'Arabic'},
                     {'id': 'de', 'text': 'German'},
                     {'id': 'en', 'text': 'English'},
                     {'id': 'en-US', 'text': 'USA English'},
                     {'id': 'es', 'text': 'Spanish'},
                     {'id': 'fr', 'text': 'French'},
                     {'id': 'he', 'text': 'Hebrew'},
                     {'id': 'it', 'text': 'Italian'},
                     {'id': 'nl', 'text': 'Dutch'},
                     {'id': 'no', 'text': 'Norwegian'},
                     {'id': 'pt', 'text': 'Portuguese'},
                     {'id': 'ru', 'text': 'Russian'},
                     {'id': 'se', 'text': 'Sami (Northern)'},
                     {'id': 'sv', 'text': 'Swedish'},
                     {'id': 'ud', 'text': 'Urdu'},
                     {'id': 'zh', 'text': 'Chinese'}]

    NEWS_CATEGORY = [{'id': 'business', 'text': 'Business'},
                     {'id': 'entertainment', 'text': 'Entertainment'},
                     {'id': 'general', 'text': 'General'},
                     {'id': 'health', 'text': 'Health'},
                     {'id': 'science', 'text': 'Science'},
                     {'id': 'sports', 'text': 'Sports'},
                     {'id': 'technology', 'text': 'Technology'}]

    TOKEN_EXP_TIME_GAP = 15 * 60
    TOKEN_ATTEMPT_TIME_GAP = 5 * 60
    MAXIMUM_TOKEN_REQUEST_COUNT = 3
