"""Made article url non-unique

Revision ID: 1d3f4d0077dd
Revises: d05175ab688b
Create Date: 2025-02-21 10:58:25.349846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d3f4d0077dd'
down_revision: Union[str, None] = 'd05175ab688b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint from 'email' column in 'users' table
    with op.batch_alter_table("article_saved") as batch_op:
        batch_op.drop_constraint("url", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add unique constraint in case of rollback
    with op.batch_alter_table("article_saved") as batch_op:
        batch_op.create_unique_constraint("url", ["url"])
    # ### end Alembic commands ###
