"""Made article url unique

Revision ID: 8b5bf2e18310
Revises: fa3c9cc025c7
Create Date: 2025-02-19 16:26:57.511263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b5bf2e18310'
down_revision: Union[str, None] = 'fa3c9cc025c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'article_saved', ['url'], unique=True, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='article_saved')
    # ### end Alembic commands ###
