"""Initial migration

Revision ID: baffd1b1ac64
Revises: 
Create Date: 2025-02-18 12:52:09.697670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'baffd1b1ac64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_email_verify_token',
        sa.Column('id', mysql.INTEGER(display_width=11),
                  autoincrement=True, nullable=False),
        sa.Column('user_ag_id', mysql.VARCHAR(length=150),
                  nullable=False),
        sa.Column('token', mysql.VARCHAR(length=255),
                  nullable=False),
        sa.Column('token_exp_timestamp', mysql.TEXT(),
                  nullable=False),
        sa.Column('token_request_count',
                  mysql.INTEGER(display_width=11),
                  autoincrement=False, nullable=True),
        sa.Column('next_token_request_timestamp', mysql.TEXT(),
                  nullable=True),
        sa.ForeignKeyConstraint(['user_ag_id'],
                                ['user.user_ag_id'],
                                name='user_email_verify_token_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
        mysql_collate='utf8mb4_unicode_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'user_details',
        sa.Column('id', mysql.INTEGER(display_width=11),
                  autoincrement=True, nullable=False),
        sa.Column('user_ag_id', mysql.VARCHAR(length=150),
                  nullable=False),
        sa.Column('first_name', mysql.VARCHAR(length=150),
                  nullable=False),
        sa.Column('last_name', mysql.VARCHAR(length=150),
                  nullable=True),
        sa.Column('phone_no', mysql.VARCHAR(length=15),
                  nullable=True),
        sa.Column('profile_pic', mysql.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(['user_ag_id'],
                                ['user.user_ag_id'],
                                name='user_details_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
        mysql_collate='utf8mb4_unicode_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index(
        'user_ag_id', 'user_details', ['user_ag_id'], unique=True,
        if_not_exists=True,)
    op.create_table(
        'user',
        sa.Column('id', mysql.INTEGER(display_width=11),
                  autoincrement=True, nullable=False),
        sa.Column('user_ag_id', mysql.VARCHAR(length=150),
                  nullable=False),
        sa.Column('username', mysql.VARCHAR(length=150),
                  nullable=False),
        sa.Column('password', mysql.VARCHAR(length=150),
                  nullable=False),
        sa.Column('is_verified', mysql.TINYINT(display_width=1),
                  autoincrement=False, nullable=True),
        sa.Column('status', mysql.TINYINT(display_width=1),
                  autoincrement=False, nullable=True),
        sa.Column('is_deleted', mysql.TINYINT(display_width=1),
                  autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.DATETIME(), nullable=True),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
        mysql_collate='utf8mb4_unicode_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index(
        'username', 'user', ['username'], unique=True,
        if_not_exists=True,)
    op.create_index(
        'user_ag_id', 'user', ['user_ag_id'], unique=True,
        if_not_exists=True,)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_ag_id', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_index('user_ag_id', table_name='user_details')
    op.drop_table('user_details')
    op.drop_table('user_email_verify_token')
    # ### end Alembic commands ###
