"""Added article table

Revision ID: fa3c9cc025c7
Revises: baffd1b1ac64
Create Date: 2025-02-19 16:17:51.618018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fa3c9cc025c7'
down_revision: Union[str, None] = 'baffd1b1ac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'article_saved',
        sa.Column('id', mysql.INTEGER(display_width=11),
                  autoincrement=True, nullable=False),
        sa.Column('user_id', mysql.VARCHAR(
            length=150), nullable=False),
        sa.Column('saved_article_ag_id', mysql.VARCHAR(
            length=150), nullable=False),
        sa.Column('title', mysql.VARCHAR(
            length=300), nullable=False),
        sa.Column('description', mysql.TEXT(), nullable=True),
        sa.Column('article_image_url',
                  mysql.TEXT(), nullable=True),
        sa.Column('url', mysql.VARCHAR(
            length=300), nullable=False),
        sa.Column('sentiment', mysql.VARCHAR(
            length=50), nullable=True),
        sa.Column('status', mysql.TINYINT(display_width=1),
                  autoincrement=False, nullable=True),
        sa.Column('is_deleted', mysql.TINYINT(display_width=1),
                  autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.DATETIME(), nullable=True),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.user_ag_id'], name='article_saved_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
        mysql_collate='utf8mb4_unicode_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index(
        'saved_article_ag_id', 'article_saved', ['saved_article_ag_id'], unique=True,
        if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_ag_id', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_index('user_ag_id', table_name='user_details')
    op.drop_table('user_details')
    op.drop_table('user_email_verify_token')
    op.drop_index('saved_article_ag_id', table_name='article_saved')
    op.drop_table('article_saved')
    # ### end Alembic commands ###
